// Simplified structure for our pages
export const categories = [
  { id: '1', name: 'Mobile Phones' },
  { id: '2', name: 'Used Phones' },
  { id: '3', name: 'Custom PC Builds' },
  { id: '4', name: 'Accessories' },
  { id: '5', name: 'Laptops' },
]

export const brands = [
  { id: '1', name: 'Apple' },
  { id: '2', name: 'Samsung' },
  { id: '3', name: 'OnePlus' },
  { id: '4', name: 'Asus' },
  { id: '5', name: 'MSI' },
  { id: '6', name: 'Lenovo' },
]

export const shops = [
  {
    id: 'shop-1',
    name: 'Shop 1 - Downtown',
    location: '123 Tech Street, Downtown',
    phone: '+1-234-567-8900',
  },
  {
    id: 'shop-2',
    name: 'Shop 2 - Midtown',
    location: '456 Digital Avenue, Midtown',
    phone: '+1-234-567-8901',
  },
]

export const products = [
  {
    id: 'prod-1',
    name: 'iPhone 15 Pro',
    description: 'Latest Apple flagship with A17 Pro chip',
    category: '1',
    brand: '1',
    price: 999,
    cost: 700,
    sku: 'IPHONE15PRO',
    stock: 15,
    shop: 'shop-2',
    image: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=400&q=80',
  },
  {
    id: 'prod-2',
    name: 'Samsung Galaxy S24',
    description: 'Flagship Samsung phone with advanced AI features',
    category: '1',
    brand: '2',
    price: 899,
    cost: 600,
    sku: 'SAMSUNGS24',
    stock: 22,
    shop: 'shop-2',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&q=80',
  },
  {
    id: 'prod-3',
    name: 'iPhone 13 (Used)',
    description: 'Excellent condition refurbished iPhone 13',
    category: '2',
    brand: '1',
    price: 599,
    cost: 400,
    sku: 'IPHONE13USED',
    stock: 8,
    shop: 'shop-1',
    image: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=400&q=80',
  },
  {
    id: 'prod-4',
    name: 'OnePlus 12',
    description: 'Fast and smooth flagship killer',
    category: '1',
    brand: '3',
    price: 649,
    cost: 450,
    sku: 'ONEPLUS12',
    stock: 12,
    shop: 'shop-2',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&q=80',
  },
  {
    id: 'prod-5',
    name: 'High-End Gaming PC',
    description: 'RTX 4090, i9-13900K, 32GB RAM',
    category: '3',
    brand: '4',
    price: 2499,
    cost: 1800,
    sku: 'GAMINGPC-HIGH',
    stock: 3,
    shop: 'shop-1',
    image: 'https://images.unsplash.com/photo-1587829191301-26d7d46a0d9f?w=400&q=80',
  },
  {
    id: 'prod-6',
    name: 'Mid-Range Gaming PC',
    description: 'RTX 4070, i7-13700K, 16GB RAM',
    category: '3',
    brand: '5',
    price: 1499,
    cost: 1100,
    sku: 'GAMINGPC-MID',
    stock: 5,
    shop: 'shop-1',
    image: 'https://images.unsplash.com/photo-1587829191301-26d7d46a0d9f?w=400&q=80',
  },
  {
    id: 'prod-7',
    name: 'Samsung Galaxy A54',
    description: 'Budget-friendly Samsung smartphone',
    category: '1',
    brand: '2',
    price: 449,
    cost: 300,
    sku: 'GALAXYA54',
    stock: 30,
    shop: 'shop-2',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&q=80',
  },
  {
    id: 'prod-8',
    name: 'Lenovo Legion 5 Pro',
    description: '16" Gaming Laptop with RTX 4060',
    category: '5',
    brand: '6',
    price: 1299,
    cost: 900,
    sku: 'LEGION5PRO',
    stock: 7,
    shop: 'shop-2',
    image: 'https://images.unsplash.com/photo-1588277235586-06cfdd865031?w=400&q=80',
  },
  {
    id: 'prod-9',
    name: 'Samsung Galaxy Z Fold 5 (Used)',
    description: 'Foldable phone in good condition',
    category: '2',
    brand: '2',
    price: 899,
    cost: 600,
    sku: 'GALAXYZFOLD5',
    stock: 2,
    shop: 'shop-1',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&q=80',
  },
  {
    id: 'prod-10',
    name: 'Budget Gaming PC',
    description: 'RTX 4050, i5-13600K, 8GB RAM',
    category: '3',
    brand: '5',
    price: 799,
    cost: 550,
    sku: 'GAMINGPC-BUDGET',
    stock: 8,
    shop: 'shop-1',
    image: 'https://images.unsplash.com/photo-1587829191301-26d7d46a0d9f?w=400&q=80',
  },
]

export const staff = [
  {
    id: 'staff-1',
    name: 'John Admin',
    email: 'admin@store.com',
    role: 'super-admin',
    shop: 'shop-1',
    status: 'active',
  },
  {
    id: 'staff-2',
    name: 'Jane Smith',
    email: 'jane@store.com',
    role: 'admin',
    shop: 'shop-2',
    status: 'active',
  },
  {
    id: 'staff-3',
    name: 'Mike Johnson',
    email: 'mike@store.com',
    role: 'staff',
    shop: 'shop-1',
    status: 'active',
  },
  {
    id: 'staff-4',
    name: 'Sarah Lee',
    email: 'sarah@store.com',
    role: 'staff',
    shop: 'shop-2',
    status: 'active',
  },
  {
    id: 'staff-5',
    name: 'Tom Davis',
    email: 'tom@store.com',
    role: 'staff',
    shop: 'shop-1',
    status: 'inactive',
  },
  {
    id: 'staff-6',
    name: 'Emma Wilson',
    email: 'emma@store.com',
    role: 'admin',
    shop: 'shop-2',
    status: 'active',
  },
]

export const dummyData = {
  products,
  categories,
  brands,
  shops,
  staff,
}
